### ISSUE TITLE
[Error] Installing SatDump on Raspberry

### ISSUE THREAD

**Issue by i6cbi** [jekhokie/raspberry-noaa-v2#1008] opened 2024-07-10 18:15 UTC
`TASK` [common : Installing predict on Raspberry Pi (armhf)] *********************
ok: [localhost]

TASK [common : Installing predict on Raspberry Pi (arm64)] *********************
skipping: [localhost]

TASK [common : Installing SatDump] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to install package: E:Impossibile aprire il file /home/pi/raspberry-noaa-v2/software/satdump_1.2.1-d5fd2f41__armhf.deb - open (2: File o directory non esistente)"}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   

Error:   Something failed with the install - please inspect the logs above
``
N.B .  File  exist

**Comment by creas002** [comment] 2024-07-10 18:35
I see an extra space added to the file name ansible is looking for

`/home/pi/raspberry-noaa-v2/software/satdump_1.2.1-d5fd2f41**_**_armhf.deb`

It should look like this 

`/home/pi/raspberry-noaa-v2/software/satdump_1.2.1-d5fd2f41_armhf.deb`

The dependencies.yml file I'm looking  does not have that space, so has your local file been modified?

$HOME/raspberry-noaa-v2/ansible/roles/common/tasks/dependencies.yml

**Comment by MihajloPi** [comment] 2024-07-10 18:55
What OS are you using? To me it looks like it's 32 bit Raspberry OS for Raspberry Pi, but which version?

**Comment by i6cbi** [comment] 2024-07-10 20:18
Il mer 10 lug 2024, 20:56 MihajloPi - YU4MPI ***@***.***> ha
scritto:

**Comment by i6cbi** [comment] 2024-07-10 22:57
> What OS are you using? To me it looks like it's 32 bit Raspberry OS for Raspberry Pi, but which version?

always the same version
description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

in software i have 
 [ satdump_1.2.1-d5fd2f41_bullseye_armhf.deb](https://github.com/MihajloPi/raspberry-noaa-v2/blob/master/software/satdump_1.2.1-d5fd2f41_bullseye_armhf.deb ]

i solved .. but others users  ??

**Comment by i6cbi** [comment] 2024-07-10 23:00
> I see an extra space added to the file name ansible is looking for
> `/home/pi/raspberry-noaa-v2/software/satdump_1.2.1-d5fd2f41**_**_armhf.deb`
Thanks Richard .. you are right --  solved myself .. but other users ??

**Comment by creas002** [comment] 2024-07-10 23:34
I was asking if you had a modified dependancies.yml file with the space. You confirmed you did. The source Repo that you just posted has the correct data and would not have the extra space. So I guess its a mystery?

[](https://github.com/MihajloPi/raspberry-noaa-v2/blob/master/ansible/roles/common/tasks/dependencies.yml)

Lines 196-201 is what drives ansiable to use the file name it reported in your error. You can see it does not have the extra space.

Perhaps Mihajlo may have an idea how your local file picked up the space.
```
- name: Installing SatDump
  become: yes
  apt:
    deb: "{{ noaa_home }}/software/satdump_1.2.1-d5fd2f41_{{ raspbian_version.stdout }}_{{ system_architecture }}.deb"
    state: present
    update_cache: no
```

**Comment by creas002** [comment] 2024-07-10 23:36
Here is the link to dependancies.yml in that repo
`https://github.com/MihajloPi/raspberry-noaa-v2/blob/master/ansible/roles/common/tasks/dependencies.yml`

**Comment by i6cbi** [comment] 2024-07-11 08:45
> I was asking if you had a modified dependancies.yml file with the space. You confirmed you did. The source Repo that you just posted has the correct data and would not have the extra space. So I guess its a mystery?
> 
> Lines 196-201 is what drives ansiable to use the file name it reported in your error. You can see it does not have the extra space.
> 
> Perhaps Mihajlo may have an idea how your local file picked up the space.
> 
> ```
> - name: Installing SatDump
>   become: yes
>   apt:
>     deb: "{{ noaa_home }}/software/satdump_1.2.1-d5fd2f41_{{ raspbian_version.stdout }}_{{ system_architecture }}.deb"
>     state: present
>     update_cache: no
> ```

yes its same .. no modified .. when i have time .. i'll try with new  fresh istallation

**Comment by creas002** [comment] 2024-07-14 13:33
Issue was duplicated and resolved via this commit in aarch64-support
https://github.com/jekhokie/raspberry-noaa-v2/commit/f58f1b736fa6c8182ec013ff1be5efe0d5c426c5

**Closed as completed** 2024-07-14 16:39 UTC
